### ISSUE TITLE
Encounter error when run the project

### ISSUE THREAD

**Issue by xuyukuan** [fraserxu/soundredux-native#10]
I get below error when I run "react-native run-android", Please advice.
<img width="928" alt="2016-09-29 7 11 34" src="https://cloud.githubusercontent.com/assets/970590/18935659/03d65152-8614-11e6-9b88-b3a8be08e1f1.png">

**Comment by xuyukuan** [comment]
update the solution:
the root cause is my android phone don't have the enough space to install the app, but it seems react native didn't report the real exception.

I uninstall some app and retry, this problem gone.

**Comment by fraserxu** [comment]
👍
