### ISSUE TITLE
filename convention

### ISSUE THREAD

**Issue by b-rucel** [fraserxu/soundredux-native#2]
When I try to rebundle code changes and update the app, it fails to build due to the file naming.

![screen shot 2015-11-11 at 11 13 00 am](https://cloud.githubusercontent.com/assets/150024/11100296/3c90a89c-8865-11e5-9803-ce56e2eb69a3.png)

/src/containers/playerContainer.js
/src/containers/songContainer.js

class PlayerContainer
class SongContainer

**Comment by fraserxu** [comment]
Hmm, it's weird, the filename on my local is the right one, but I'm sure I've pushed all my changes.

```
➜  containers git:(master) ll
total 40
-rw-r--r--  1 fraserxu  staff   712B Nov 12 00:31 MainContainer.js
-rw-r--r--  1 fraserxu  staff   788B Nov 12 00:35 PlayerContainer.js
-rw-r--r--  1 fraserxu  staff   722B Nov 12 01:00 SearchContainer.js
-rw-r--r--  1 fraserxu  staff   673B Nov 12 00:59 SongContainer.js
-rw-r--r--  1 fraserxu  staff   960B Nov 12 00:29 app.js
```

Let me check again.

**Comment by b-rucel** [comment]
![screen shot 2015-11-11 at 7 49 34 pm](https://cloud.githubusercontent.com/assets/150024/11110147/694dc8a4-88ad-11e5-88f4-60f10753a6bf.png)

**Comment by b-rucel** [comment]
I can fork and submit pull request if you like.

**Comment by xeodou** [comment]
I know the issue, it's caused by the Mac OSX file system. @fraserxu You need do it's rename files.

**Comment by fraserxu** [comment]
@b-rucel Thanks for report! Fixed!!!
