### ISSUE TITLE
Quick question about use of let

### ISSUE THREAD

**Issue by JonathanZWhite** [fraserxu/soundredux-native#6]
Quick question. I noticed that in some of your components you are using `let` instead of `const` despite not needing to make any explicit changes to the variable. Is there any reasoning behind this? Or is it just preference?

https://github.com/fraserxu/soundredux-native/blob/7e263b8cbc37fd805df2330d091706ccac07aa79/src/components/Search.js#L32

**Comment by fraserxu** [comment]
Sorry, I'm just being lazy...

**Comment by JonathanZWhite** [comment]
Oh no problem! I just wanted to make sure I wasn't missing something. Cool, thanks for making this repo public, it's been a great help in building React Native apps :)
